/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_Cls */

#ifndef _Included_pkg_Cls
#define _Included_pkg_Cls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pkg_Cls
 * Method:    f
 * Signature: (ILjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_pkg_Cls_f
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     pkg_Cls
 * Method:    pa
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_pkg_Cls_pa
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     pkg_Cls
 * Method:    pStringArray
 * Signature: ([Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_pkg_Cls_pStringArray
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     pkg_Cls
 * Method:    accessMethod
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_pkg_Cls_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     pkg_Cls
 * Method:    staticNativeMethod
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_pkg_Cls_staticNativeMethod
  (JNIEnv *, jclass);

/*
 * Class:     pkg_Cls
 * Method:    nativeException
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_pkg_Cls_nativeException
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
